#!/bin/bash

# create-test-prs.sh
# Creates test PRs for each scenario branch to trigger backport agent evaluation
#
# Usage:
#   ./scripts/create-test-prs.sh [options]
#
# Options:
#   --dry-run    Show what would be created without creating PRs
#   --force      Recreate PRs even if they already exist
#   --help       Show this help message
#
# Requirements:
#   - gh CLI installed and authenticated
#   - Repository must have remote origin configured
#
# Output:
#   - Creates PR from each scenario branch to main
#   - Outputs PR numbers for tracking in pr-numbers.txt

set -euo pipefail

# Configuration
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET_BRANCH="main"
DRY_RUN=false
FORCE=false

# Scenario definitions (array of "num:name" pairs)
SCENARIOS=(
    "1:Content Conflict"
    "2:Rename/Modify Conflict"
    "3:Rename/Rename Conflict"
    "4:Modify/Delete Conflict"
    "5:Add/Add Conflict"
    "6:Context Conflict"
    "7:Dependency Conflict"
    "8:Multi-File Conflict"
)

get_scenario_name() {
    local num="$1"
    for entry in "${SCENARIOS[@]}"; do
        local entry_num="${entry%%:*}"
        if [[ "$entry_num" == "$num" ]]; then
            echo "${entry#*:}"
            return 0
        fi
    done
    echo ""
}

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

show_help() {
    head -n 20 "$0" | grep "^#" | sed 's/^# \?//'
    exit 0
}

check_requirements() {
    log_info "Checking requirements..."

    # Check gh CLI
    if ! command -v gh &> /dev/null; then
        log_error "gh CLI is not installed. Install from https://cli.github.com/"
        exit 1
    fi

    # Check authentication
    if ! gh auth status &> /dev/null; then
        log_error "gh CLI is not authenticated. Run: gh auth login"
        exit 1
    fi

    # Check git remote
    if ! git -C "$REPO_ROOT" remote get-url origin &> /dev/null; then
        log_error "No git remote 'origin' configured"
        exit 1
    fi

    log_success "All requirements satisfied"
}

get_pr_for_branch() {
    local branch="$1"
    # Get open PR number for this branch (if exists)
    gh pr list --head "$branch" --base "$TARGET_BRANCH" --state open --json number --jq ".[0].number" 2>/dev/null || echo ""
}

create_pr_for_scenario() {
    local scenario_num="$1"
    local scenario_name=$(get_scenario_name "$scenario_num")
    local scenario_padded=$(printf "%02d" "$scenario_num")
    local scenario_slug=$(echo "${scenario_name}" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr '/' '-')
    local branch_name="scenario-${scenario_padded}-${scenario_slug}"

    log_info "Processing scenario ${scenario_padded}: ${scenario_name}"

    # Check if branch exists
    if ! git -C "$REPO_ROOT" rev-parse --verify "origin/${branch_name}" &> /dev/null; then
        log_warning "Branch ${branch_name} does not exist, skipping"
        return 1
    fi

    # Check for existing PR
    local existing_pr
    existing_pr=$(get_pr_for_branch "$branch_name")

    if [[ -n "$existing_pr" ]] && [[ "$FORCE" == "false" ]]; then
        log_info "PR already exists: #${existing_pr} (use --force to recreate)"
        echo "${scenario_padded}:${existing_pr}"
        return 0
    fi

    # Close existing PR if force mode
    if [[ -n "$existing_pr" ]] && [[ "$FORCE" == "true" ]]; then
        log_info "Closing existing PR #${existing_pr}"
        if [[ "$DRY_RUN" == "false" ]]; then
            gh pr close "$existing_pr" --comment "Recreating PR for fresh evaluation"
        fi
    fi

    # Prepare PR body
    local pr_title="Test Scenario ${scenario_padded}: ${scenario_name}"
    local pr_body
    pr_body=$(cat <<EOF
## Backport Test Scenario ${scenario_padded}

**Scenario:** ${scenario_name}

This PR represents a feature/fix that should be backported to \`release-v1.0\`.

### Instructions for Agent

Please backport this change to \`release-v1.0\` by commenting:

\`\`\`
@agent-backport backport to release-v1.0
\`\`\`

### Evaluation Criteria

This scenario tests the agent's ability to:
- Detect and resolve merge conflicts intelligently
- Apply semantic understanding of code changes
- Maintain compatibility with the target branch
- Provide clear explanations of resolution decisions

### Documentation

- [Scenario Description](../scenarios/${scenario_padded}-${scenario_slug}/README.md)
- [Expected Resolution](../scenarios/${scenario_padded}-${scenario_slug}/expected-resolution.md)
- [Full Test Suite README](../README.md)

---

*Generated by \`create-test-prs.sh\` for automated backport agent evaluation*
EOF
)

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY RUN] Would create PR:"
        echo "  Title: ${pr_title}"
        echo "  Branch: ${branch_name} -> ${TARGET_BRANCH}"
        echo "  Body preview: $(echo "$pr_body" | head -n 3)..."
        return 0
    fi

    # Create PR
    log_info "Creating PR: ${pr_title}"
    local pr_number
    local repo_url
    local repo_slug
    repo_url=$(git -C "$REPO_ROOT" remote get-url origin)
    repo_slug=$(echo "$repo_url" | sed 's|.*github\.com[:/]||' | sed 's|\.git$||')
    pr_number=$(gh pr create \
        --title "$pr_title" \
        --body "$pr_body" \
        --base "$TARGET_BRANCH" \
        --head "$branch_name" \
        --repo "$repo_slug" \
        2>&1 | grep -oE "[0-9]+\$" || echo "")

    if [[ -n "$pr_number" ]]; then
        log_success "Created PR #${pr_number}"
        echo "${scenario_padded}:${pr_number}"
    else
        log_error "Failed to create PR for scenario ${scenario_padded}"
        return 1
    fi
}

main() {
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --dry-run)
                DRY_RUN=true
                shift
                ;;
            --force)
                FORCE=true
                shift
                ;;
            --help|-h)
                show_help
                ;;
            *)
                log_error "Unknown option: $1"
                show_help
                ;;
        esac
    done

    cd "$REPO_ROOT"

    log_info "Starting test PR creation..."
    log_info "Repository: $REPO_ROOT"
    log_info "Target branch: $TARGET_BRANCH"
    log_info "Dry run: $DRY_RUN"
    log_info "Force recreate: $FORCE"
    echo ""

    check_requirements
    echo ""

    # Track results
    local pr_numbers_file="$REPO_ROOT/pr-numbers.txt"
    local temp_file
    temp_file=$(mktemp)

    local success_count=0
    local skip_count=0
    local fail_count=0

    # Create PRs for each scenario
    for entry in "${SCENARIOS[@]}"; do
        local scenario_num="${entry%%:*}"
        if create_pr_for_scenario "$scenario_num" >> "$temp_file"; then
            ((success_count++))
        else
            if [[ $? -eq 1 ]]; then
                ((skip_count++))
            else
                ((fail_count++))
            fi
        fi
        echo ""
    done

    # Save PR numbers
    if [[ "$DRY_RUN" == "false" ]] && [[ -s "$temp_file" ]]; then
        mv "$temp_file" "$pr_numbers_file"
        log_success "PR numbers saved to: $pr_numbers_file"
    else
        rm -f "$temp_file"
    fi

    # Summary
    echo ""
    log_info "Summary:"
    echo "  Created: $success_count"
    echo "  Skipped: $skip_count"
    echo "  Failed: $fail_count"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_warning "This was a dry run. No PRs were actually created."
        log_info "Run without --dry-run to create PRs"
    fi

    if [[ $fail_count -gt 0 ]]; then
        exit 1
    fi
}

main "$@"
